---
title: 'TidyTuesday: Bob Ross Paintings'
author: "David Jackson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DBI)
library(odbc)
library(scales)
library(tidyverse)
library(janitor)
library(writexl)
library(knitr)
library(kableExtra)
library(reshape2)
library(igraph)
library(RColorBrewer)
```

## Bob Ross Paintings

#### Import and Clean Data


```{r}
rm(list=ls())
## https://db.rstudio.com/databases/microsoft-sql-server/
con <- DBI::dbConnect(odbc::odbc(), 
                      Driver = "SQL Server", 
                      Server = "localhost\\SQLEXPRESS", 
                      Database = "TidyTuesday", 
                      Trusted_Connection = "True")

# dbListTables(con)
```
```{r }
bob_ross <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-02-21/bob_ross.csv') %>%
  janitor::clean_names() %>%
 select(-img_src,- youtube_src, - color_hex, - painting_index)
```

#### Data Wrangling

```{r}
br_cleaner <- bob_ross %>%
  mutate(colors = str_remove_all(colors, "\\[|\\]"))
```
```{r}
br_cleaner <-  br_cleaner %>%
  mutate(colors = str_replace(colors, "Phthalo Green\r\n", "Phthalo Green"))
```
```{r}
br_cleaner <- br_cleaner %>%  separate(colors, into = paste0("color", 1:10), sep = ",")
```


```{r}
dbWriteTable(con, "bob_ross",br_cleaner ,overwrite=TRUE)
# dbListFields(con,"bob_ross")

dbGetQuery(con,"select count(*) FROM bob_ross")
```

```{r}
# write_xlsx(br_cleaner,path="bob_rose.xlsx")
```

```{r}

ggplot(br_cleaner, aes(x = num_colors)) +
  geom_histogram(bins = 20, fill = "blue", alpha = 0.5) +
  xlab("Number of Colors Used") +
  ylab("Count") +
  ggtitle("Distribution of Number of Colors Used")

```
```{r}
colors <-  br_cleaner %>%
  select(color1:color10) %>%
  pivot_longer(cols = everything(), values_to = "color") %>%
  group_by(color) %>%
  summarize(count = n()) %>%
  arrange(desc(count)) %>% drop_na()
```
```{r}
colors %>%
  ggplot(aes(x = reorder(color, count), y = count)) +
  geom_col(fill = "green") +
  coord_flip() +
  xlab("Color") +
  ylab("Count") +
  ggtitle("Most Commonly Used Colors")

```
```{r}
ggplot(br_cleaner, aes(x = black_gesso, y = num_colors)) +
  geom_boxplot(fill = "gray", alpha = 0.5) +
  xlab("Black Gesso Used") +
  ylab("Number of Colors Used") +
  ggtitle("Assoc Between Black Gesso and Number of Colors Used")

```

```{r}
# library(tidyverse)

# Read in the Bob Ross painting data
# bob_ross_data <- read_csv("bob_ross_data.csv")

# Select only the columns with numeric data
numeric_cols <- c("num_colors", "black_gesso", "bright_red", "burnt_umber", 
                  "cadmium_yellow", "dark_sienna", "indian_red", "indian_yellow", 
                  "liquid_black", "liquid_clear", "midnight_black", "phthalo_blue", 
                  "phthalo_green", "prussian_blue", "sap_green", "titanium_white", 
                  "van_dyke_brown", "yellow_ochre", "alizarin_crimson")

numeric_data <- br_cleaner %>%
  select(all_of(numeric_cols))

# Calculate the correlation matrix
cor_matrix <- cor(numeric_data, use = "complete.obs")

# Convert the correlation matrix to a data frame and reshape it for plotting
cor_data <- cor_matrix %>%
  as.data.frame() %>%
  rownames_to_column("variable1") %>%
  pivot_longer(-variable1, names_to = "variable2", values_to = "correlation")
```
```{r}
# Plot the correlation matrix as a heatmap
ggplot(cor_data, aes(x = variable1, y = variable2, fill = correlation)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0) +
  theme_minimal() +
  ggtitle("Correlation Matrix for Bob Ross Painting Data") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
```{r}
cor_df <- as.data.frame(cor_matrix)
cor_table <- kable(cor_df, digits = 3, caption = "Correlation Matrix for Bob Ross Painting Data") %>%
  kable_styling(bootstrap_options = c("striped", "hover"), 
                full_width = FALSE, 
                font_size = 12) %>%
  column_spec(1, bold = TRUE, color = "white", background = "#0073C2")

# Print the table
cor_table
```

```{r}

# Convert season to a factor variable
br_cleaner$season <- factor(br_cleaner$season)

# Create the violin plot
ggplot(br_cleaner, aes(x = season, y = num_colors, fill = season)) +
  geom_violin() +
  labs(title = "Distribution of Number of Colors Used by Season",
       x = "Season", y = "Number of Colors") +
  theme_minimal()


```

```{r}

# Convert season to a factor variable
br_cleaner$season <- factor(br_cleaner$season)

# Create the violin plot
ggplot(br_cleaner, aes(x = season, y = num_colors, fill = season)) +
  geom_boxplot() +
  labs(title = "Distribution of Number of Colors Used by Season",
       x = "Season", y = "Number of Colors") +
  theme_minimal()


```

```{r}
# Extract correlation matrix
cor_matrix <- cor(numeric_data[,4:ncol(numeric_data)])

# Loop over each color and extract highest correlated color
for (i in 1:ncol(cor_matrix)) {
  corr_vals <- cor_matrix[,i]
  abs_corr_vals <- abs(corr_vals)
  max_corr_index <- which.max(abs_corr_vals)
  max_corr_color <- colnames(cor_matrix)[max_corr_index]
  print(paste0("Color ", colnames(cor_matrix)[i], " is most correlated with color ", max_corr_color))
}

```

```{r}
# # Calculate the correlations
# cor_df <- numeric_data %>%
#   select(-c(1:3)) %>%  # Remove non-color columns
#   cor(use = "pairwise.complete.obs") %>%  # Calculate correlations
#   as.data.frame() %>%  # Convert to data frame
#   rownames_to_column(var = "color1") %>%  # Convert row names to a column
#   gather(key = "color2", value = "correlation", -color1) %>%  # Convert to long format
# 
# # Filter for correlations above a certain threshold
# cor_threshold <- 0.7
# high_correlations <- cor_df %>%
#   filter(abs(correlation) > cor_threshold)
# 
# # Save the high correlations to a data frame
# high_correlations_df <- high_correlations %>%
#   arrange(desc(abs(correlation)))
# 
# # View the first few rows of the high correlations data frame
# head(high_correlations_df)

```

```{r}

# Convert the correlation matrix to a long format dataframe
melted_df <- melt(cor_df)

# Plot the heatmap
ggplot(melted_df, aes(Var1, Var2, fill = value)) +
  geom_tile() +
  scale_fill_gradient(low = "#F0FFFF", high = "#8B0000") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


```{r}
# Create an edge list from the correlation matrix
edges <- data.frame(expand.grid(rownames(cor_df), rownames(cor_df)))
edges$cor <- as.vector(cor_df)

# Filter out the self-edges
edges <- edges[edges$Var1 != edges$Var2, ]

# Create a graph from the edge list
g <- graph_from_data_frame(edges, directed = FALSE)

# Plot the graph using Fruchterman-Reingold layout
plot(g, layout = layout.fruchterman.reingold(g), edge.width = abs(E(g)$cor) * 5, edge.color = ifelse(E(g)$cor > 0, "blue", "red"))


```

```{r}
# Load necessary libraries

# Calculate the average number of colors used for each season
avg_colors_by_season <- br_cleaner %>%
  group_by(season) %>%
  summarize(avg_colors = mean(num_colors))

# Create the bar chart
ggplot(avg_colors_by_season, aes(x = season, y = avg_colors, fill = season)) +
  geom_col() +
  labs(x = "Season", y = "Average Number of Colors Used") +
  theme_minimal()


```





